### ISSUE TITLE
important URLS

### ISSUE THREAD

**Issue by samiheikki** [Identiofi/adrev#1]

**Comment by samiheikki** [comment]
vue-material: https://marcosmoura.github.io/vue-material/#/

**Comment by samiheikki** [comment]
color design: https://material.google.com/style/color.html

**Comment by samiheikki** [comment]
icons: https://material.io/icons/

**Comment by samiheikki** [comment]
vue-router: https://router.vuejs.org/en/

**Comment by samiheikki** [comment]
Voidaanko sulkea? Ping @ahie @teemusta @Korganiof

**Comment by teemusta** [comment]
Kyll mun puolesta

27.3.2017 9.08 ip. "Sami Suo-Heikki" <notifications@github.com> kirjoitti:

Voidaanko sulkea? Ping @ahie <https://github.com/ahie> @teemusta
<https://github.com/teemusta> @Korganiof <https://github.com/Korganiof>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Identiofi/adrev/issues/1#issuecomment-289518602>, or mute
the thread
